//No5a

  SELECT * ,CLIENT_NAME,BIRTH_DATE
	FROM T_POLICY 
	    JOIN T_CLIENT USING (client_number)
        WHERE policy_submit_date >= '1/15/2018' AND EXTRACT(MONTH FROM BIRTH_DATE) = 9


  //No5b
      
  SELECT * ,AGENT_NAME
	FROM T_POLICY 
	    JOIN T_AGENT USING (agent_code)
        WHERE POLICY_STATUS = 'INFORCE' AND agent_office = 'JAKARTA' 


//No5c

SELECT AGENT_CODE,AGENT_NAME,POLICY_NUMBER,COMMISSION,PREMIUM,(COMMISSION/PREMIUM) *100 AS BASIC_COMMISSION
    FROM T_AGENT
         JOIN T_POLICY USING(agent_code)
         GROUP BY AGENT_CODE,AGENT_NAME,POLICY_NUMBER,COMMISSION,PREMIUM
  

//No5d
SELECT POLICY_SUBMIT_DATE,POLICY_SUBMIT_DATE + interval '30' day
        AS POLICY_DUE_DATE
        FROM T_POLICY;
  

//No5e
SELECT AGENT_CODE,AGENT_NAME,POLICY_NUMBER,COMMISSION,PREMIUM,
    premium*discount/100 AS PERMIUM_DISCOUNT
    FROM T_AGENT
         JOIN T_POLICY USING(agent_code)
         WHERE premium*discount/100 <='1000000'
         GROUP BY AGENT_CODE,AGENT_NAME,POLICY_NUMBER,COMMISSION,PREMIUM
         ORDER BY PERMIUM_DISCOUNT



